package com.amicbeam.beyondcraftlines.common.runtime;

import com.amicbeam.beyondcraftlines.CraftlinesConfig;
import com.amicbeam.beyondcraftlines.common.block.CraftlineDashboardBlock;
import com.amicbeam.beyondcraftlines.common.crafting.PlanningSnapshotService;
import com.amicbeam.beyondcraftlines.common.crafting.RecipePlan;
import com.amicbeam.beyondcraftlines.common.crafting.RecipePlanningService;
import com.amicbeam.beyondcraftlines.common.dashboard.*;
import com.amicbeam.beyondcraftlines.common.data.DeviceBindingRegistry;
import com.amicbeam.beyondcraftlines.common.init.CraftlinesBlockEntities;
import com.amicbeam.beyondcraftlines.common.menu.DashboardConfigMenu;
import com.amicbeam.beyondcraftlines.common.util.NbtCompat;
import com.wintercogs.beyonddimensions.api.dimensionnet.DimensionsNet;
import com.wintercogs.beyonddimensions.api.storage.key.IStackKey;
import com.wintercogs.beyonddimensions.api.storage.key.StackKeyRegistry;
import com.wintercogs.beyonddimensions.api.storage.key.impl.ItemStackKey;
import com.wintercogs.beyonddimensions.common.block.entity.NetedBlockEntity;
import net.minecraft.core.BlockPos;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.SimpleMenuProvider;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.storage.ValueInput;
import net.minecraft.world.level.storage.ValueOutput;
import java.util.Set;
import java.util.UUID;

import static com.amicbeam.beyondcraftlines.common.localization.OrderStatusMessage.encode;

public final class CraftlineDashboardBlockEntity extends NetedBlockEntity {
    private static final String DATA_TAG="dashboard_data";
    private IStackKey<?> target=ItemStackKey.EMPTY;private long desiredAmount=1;private DashboardStockMode stockMode=DashboardStockMode.NETWORK;private DashboardRedstoneMode redstoneMode=DashboardRedstoneMode.IGNORE;private DashboardRecipeConfig recipe=DashboardRecipeConfig.EMPTY;private UUID owner=new UUID(0,0),activeOrder;private int checkTicks;private boolean wasPowered,pulsePending;private long lastObserved,activeOrderDelivered;private String lastError="";
    public CraftlineDashboardBlockEntity(BlockPos pos,BlockState state){super(CraftlinesBlockEntities.CRAFTLINE_DASHBOARD.get(),pos,state);}
    public IStackKey<?> target(){return target;}public long desiredAmount(){return desiredAmount;}public DashboardStockMode stockMode(){return stockMode;}public DashboardRedstoneMode redstoneMode(){return redstoneMode;}public DashboardRecipeConfig recipe(){return recipe;}public UUID activeOrder(){return activeOrder;}public long lastObserved(){return lastObserved;}public String lastError(){return lastError;}public boolean isActiveDashboard(){return getNetId()>=0&&!target.isEmpty()&&recipe.configured();}
    public void setOwner(UUID value){if(value!=null){owner=value;syncChanged();}}
    public boolean configure(ServerPlayer player,IStackKey<?> next,long desired,DashboardStockMode stock,DashboardRedstoneMode redstone){if(!mayConfigure(player)||desired<1)return false;if(next==null)next=ItemStackKey.EMPTY;boolean changed=target.isEmpty()!=next.isEmpty()||!target.isEmpty()&&!com.amicbeam.beyondcraftlines.common.crafting.StackKeyMatch.exact(target,next);target=next;desiredAmount=desired;stockMode=stock==null?DashboardStockMode.NETWORK:stock;redstoneMode=redstone==null?DashboardRedstoneMode.IGNORE:redstone;owner=player.getUUID();if(changed)recipe=DashboardRecipeConfig.EMPTY;lastError="";CraftlineDashboardIndex.refresh(this);syncChanged();return true;}
    public boolean saveRecipe(ServerPlayer player,DashboardRecipeConfig value){int limit=Math.min(65536,CraftlinesConfig.MAX_DASHBOARD_RECIPE_BYTES.get());if(!mayConfigure(player)||value==null||value.choiceCount()>CraftlinesConfig.MAX_DASHBOARD_RECIPE_CHOICES.get()||value.estimatedBytes()>limit)return false;recipe=value;owner=player.getUUID();lastError="";CraftlineDashboardIndex.refresh(this);syncChanged();return true;}
    public boolean mayConfigure(ServerPlayer player){if(player==null||player.blockPosition().distSqr(worldPosition)>64)return false;DimensionsNet net=getNet();return net!=null&&(net.isOwner(player)||net.isManager(player)||net.getPlayers().contains(player.getUUID()));}
    public void openConfiguration(ServerPlayer player){if(!mayConfigure(player))return;player.openMenu(new SimpleMenuProvider((id,inv,ignored)->new DashboardConfigMenu(id,inv,worldPosition,this),Component.translatable("menu.beyond_craftlines.dashboard")),buffer->DashboardConfigMenu.write(buffer,worldPosition,this));}
    public static void serverTick(Level level,BlockPos pos,BlockState state,CraftlineDashboardBlockEntity d){if(!(level instanceof ServerLevel server))return;boolean powered=level.hasNeighborSignal(pos),rising=powered&&!d.wasPowered;d.wasPowered=powered;if(rising)d.pulsePending=true;if(++d.checkTicks<CraftlinesConfig.DASHBOARD_CHECK_INTERVAL_TICKS.get())return;d.checkTicks=0;boolean pulse=d.pulsePending;d.pulsePending=false;if(!d.redstoneMode.allows(powered,pulse)||d.target.isEmpty()||!d.recipe.configured())return;d.checkAndOrder(server,state);}
    private void checkAndOrder(ServerLevel level,BlockState state){DimensionsNet net=getNet();if(net==null){recordError("network unavailable");return;}RecipeOrderSavedData orders=RecipeOrderSavedData.get(level.getServer());if(activeOrder!=null){RecipeOrderJob existing=orders.get(activeOrder);if(existing!=null&&!terminal(existing.status()))return;activeOrder=null;activeOrderDelivered=0;syncChanged();}int active=(int)orders.active().stream().filter(j->j.networkId()==getNetId()&&j.origin()==OrderOrigin.AUTOMATIC).count();if(!AutomaticOrderPolicy.canCreate(active,CraftlinesConfig.MAX_ACTIVE_AUTOMATIC_ORDERS_PER_NETWORK.get()))return;BlockPos supportPosition=CraftlineDashboardBlock.supportPos(worldPosition,state);net.minecraft.core.Direction supportSide=CraftlineDashboardBlock.supportSide(state);if(stockMode==DashboardStockMode.CONTAINER&&!BoundMachineAutomation.supportsResource(level,supportPosition,supportSide,target)){updateObserved(0);recordError("dashboard_container_unavailable");return;}long stored=stockMode==DashboardStockMode.NETWORK?networkAmount(net):BoundMachineAutomation.countPresent(level,supportPosition,supportSide,target);updateObserved(stored);long deficit=AutomaticOrderPolicy.deficit(desiredAmount,stored);if(deficit<=0){recordError("");return;}if(stockMode==DashboardStockMode.CONTAINER){long capacity=BoundMachineAutomation.insertCapacity(level,supportPosition,supportSide,target,deficit);if(capacity<=0){recordError("dashboard_container_blocked");return;}long transferred=transferNetworkStock(net,level,supportPosition,supportSide,deficit,capacity);if(transferred>0){stored=BoundMachineAutomation.countPresent(level,supportPosition,supportSide,target);updateObserved(stored);deficit=AutomaticOrderPolicy.deficit(desiredAmount,stored);if(deficit<=0){recordError("");return;}capacity=BoundMachineAutomation.insertCapacity(level,supportPosition,supportSide,target,deficit);if(capacity<=0){recordError("dashboard_container_blocked");return;}}deficit=AutomaticOrderPolicy.transferable(deficit,capacity);}try{var snapshot=PlanningSnapshotService.capture(getNetId());Set<String> families=DeviceBindingRegistry.availableFamilies(level.getServer(),getNetId());RecipePlan plan=largestCraftable(level,deficit,snapshot,families);if(plan==null||!plan.craftable()||plan.requested()<=0)return;RecipeOrderJob job=RecipeOrderService.enqueueAutomaticValidated(level,owner,getNetId(),plan.target(),plan.requested(),recipe.blockingMode(),stockMode==DashboardStockMode.CONTAINER?OrderOutputDestination.CONTAINER:OrderOutputDestination.NETWORK,plan);activeOrder=job.id();activeOrderDelivered=0;recordError("");}catch(RuntimeException e){recordError(e.getMessage());}}
    RecipeOrderJob deliverCompletedOrder(DimensionsNet network,RecipeOrderJob job){if(stockMode!=DashboardStockMode.CONTAINER||activeOrder==null||!activeOrder.equals(job.id())||!(level instanceof ServerLevel serverLevel))return job.with(RecipeOrderJob.Status.PAUSED,encode("waiting_dashboard_container"));BlockState state=getBlockState();BlockPos supportPosition=CraftlineDashboardBlock.supportPos(worldPosition,state);net.minecraft.core.Direction supportSide=CraftlineDashboardBlock.supportSide(state);if(!BoundMachineAutomation.supportsResource(serverLevel,supportPosition,supportSide,target)){recordError("dashboard_container_unavailable");return job.with(RecipeOrderJob.Status.PAUSED,encode("waiting_dashboard_container"));}long remaining=Math.max(0,job.requested()-activeOrderDelivered);if(remaining<=0){recordError("");return job.with(RecipeOrderJob.Status.COMPLETE,"");}long capacity=BoundMachineAutomation.insertCapacity(serverLevel,supportPosition,supportSide,target,remaining);if(capacity<=0){updateObserved(BoundMachineAutomation.countPresent(serverLevel,supportPosition,supportSide,target));recordError("dashboard_container_blocked");return job.with(RecipeOrderJob.Status.PAUSED,encode("waiting_dashboard_container_space"));}long requested=Math.min(remaining,capacity);com.wintercogs.beyonddimensions.api.storage.key.KeyAmount taken=network.getUnifiedStorage().extract(target,requested,false,false);if(taken.isEmpty())return job.with(RecipeOrderJob.Status.PAUSED,encode("waiting_final_output"));long inserted=BoundMachineAutomation.insert(serverLevel,supportPosition,supportSide,taken.key(),taken.amount());long rejected=Math.max(0,taken.amount()-inserted);if(rejected>0)network.getUnifiedStorage().insert(taken.key(),rejected,false);if(inserted>0){activeOrderDelivered=Math.min(job.requested(),activeOrderDelivered+inserted);updateObserved(BoundMachineAutomation.countPresent(serverLevel,supportPosition,supportSide,target));syncChanged();}if(activeOrderDelivered>=job.requested()){recordError("");return job.with(RecipeOrderJob.Status.COMPLETE,"");}recordError("dashboard_container_blocked");return job.with(RecipeOrderJob.Status.PAUSED,encode(inserted>0?"waiting_dashboard_container_space":"waiting_dashboard_container"));}
    private long transferNetworkStock(DimensionsNet network,ServerLevel level,BlockPos position,net.minecraft.core.Direction side,long deficit,long capacity){long requested=AutomaticOrderPolicy.transferable(deficit,capacity);if(requested<=0)return 0;com.wintercogs.beyonddimensions.api.storage.key.KeyAmount taken=network.getUnifiedStorage().extract(target,requested,false,false);if(taken.isEmpty())return 0;long inserted=BoundMachineAutomation.insert(level,position,side,taken.key(),taken.amount());long rejected=Math.max(0,taken.amount()-inserted);if(rejected>0)network.getUnifiedStorage().insert(taken.key(),rejected,false);return inserted;}
    private RecipePlan largestCraftable(ServerLevel level,long deficit,PlanningSnapshotService.Snapshot snapshot,Set<String> families){RecipePlan full=RecipePlanningService.validateFixed(level,target,deficit,snapshot,families,recipe.overrides());if(full.craftable()&&recipe.overrides().completelyResolves(full))return full;long low=0,high=deficit;RecipePlan best=null;while(low<high){long middle=low+(high-low+1)/2;RecipePlan candidate=RecipePlanningService.validateFixed(level,target,middle,snapshot,families,recipe.overrides());if(candidate.craftable()&&recipe.overrides().completelyResolves(candidate)){low=middle;best=candidate;}else high=middle-1;}return low<=0?null:best!=null&&best.requested()==low?best:RecipePlanningService.validateFixed(level,target,low,snapshot,families,recipe.overrides());}
    private long networkAmount(DimensionsNet net){long total=0;for(var stored:net.getUnifiedStorage().getStorage())if(com.amicbeam.beyondcraftlines.common.crafting.StackKeyMatch.exact(target,stored.key()))total=total>Long.MAX_VALUE-Math.max(0,stored.amount())?Long.MAX_VALUE:total+Math.max(0,stored.amount());return total;}
    private void recordError(String value){String next=value==null?"":value;if(next.length()>256)next=next.substring(0,256);if(!next.equals(lastError)){lastError=next;syncChanged();}}
    private void updateObserved(long value){value=Math.max(0,value);if(value!=lastObserved){lastObserved=value;syncChanged();}}
    private static boolean terminal(RecipeOrderJob.Status s){return s==RecipeOrderJob.Status.COMPLETE||s==RecipeOrderJob.Status.CANCELLED||s==RecipeOrderJob.Status.ERROR;}
    private void syncChanged(){setChanged();if(level!=null)level.sendBlockUpdated(worldPosition,getBlockState(),getBlockState(),3);}
    @Override public void onLoad(){super.onLoad();if(level!=null&&!level.isClientSide())CraftlineDashboardIndex.refresh(this);}
    @Override public void setRemoved(){CraftlineDashboardIndex.remove(this);super.setRemoved();}
    @Override public void onNetChange(){super.onNetChange();CraftlineDashboardIndex.refresh(this);}
    @Override protected void saveAdditional(ValueOutput output){super.saveAdditional(output);CompoundTag tag=new CompoundTag();tag.putLong("desired",desiredAmount);tag.putString("stock_mode",stockMode.id());tag.putString("redstone_mode",redstoneMode.id());tag.putString("owner",owner.toString());if(activeOrder!=null)tag.putString("active_order",activeOrder.toString());tag.putLong("active_order_delivered",activeOrderDelivered);tag.putLong("last_observed",lastObserved);tag.putString("last_error",lastError);if(!target.isEmpty()){tag.putString("target_type",target.getTypeId().toString());tag.put("target",target.serializeNBT(lookupProvider()));}if(recipe.configured())tag.put("recipe",recipe.save());output.store(DATA_TAG,CompoundTag.CODEC,tag);}
    @Override protected void loadAdditional(ValueInput input){super.loadAdditional(input);CompoundTag tag=input.read(DATA_TAG,CompoundTag.CODEC).orElseGet(CompoundTag::new);desiredAmount=Math.max(1,tag.getLongOr("desired",1));stockMode=DashboardStockMode.byId(tag.getStringOr("stock_mode","network"));redstoneMode=DashboardRedstoneMode.byId(tag.getStringOr("redstone_mode","ignore"));try{owner=UUID.fromString(tag.getStringOr("owner",""));}catch(RuntimeException ignored){owner=new UUID(0,0);}try{activeOrder=UUID.fromString(tag.getStringOr("active_order",""));}catch(RuntimeException ignored){activeOrder=null;}activeOrderDelivered=Math.max(0,tag.getLongOr("active_order_delivered",0));lastObserved=Math.max(0,tag.getLongOr("last_observed",0));lastError=tag.getStringOr("last_error","");Identifier type=Identifier.tryParse(tag.getStringOr("target_type",""));target=ItemStackKey.EMPTY;if(type!=null&&tag.contains("target"))try{target=StackKeyRegistry.getType(type).deserializeNBT(tag.getCompoundOrEmpty("target"),input.lookup());}catch(RuntimeException|LinkageError ignored){}recipe=tag.contains("recipe")?DashboardRecipeConfig.load(tag.getCompoundOrEmpty("recipe")):DashboardRecipeConfig.EMPTY;}
    @Override public CompoundTag getUpdateTag(HolderLookup.Provider registries){CompoundTag tag=super.getUpdateTag(registries);CompoundTag data=tag.getCompoundOrEmpty(DATA_TAG);data.remove("recipe");tag.put(DATA_TAG,data);return tag;}
}
